# -*- coding: utf-8 -*-
"""HGNN in a another approach

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1syR4YGisd5bhOkFLdzmFcKpx2spJosfh

HGNN in a another approach

Setup & Imports
"""

# -*- coding: utf-8 -*-
# Part 1: Setup & Imports

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install required libraries
!pip install pandas numpy torch scikit-learn hypernetx networkx umap-learn

# Imports
import ast
import os
import math
import random
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_auc_score, average_precision_score, accuracy_score,
    f1_score, precision_recall_curve, roc_curve
)
from sklearn.preprocessing import normalize as sk_normalize
from sklearn.metrics.pairwise import cosine_similarity
import hypernetx as hnx
import networkx as nx
import matplotlib.pyplot as plt

"""Utilities & Hypergraph Construction"""

# Part 2: Utilities & Hypergraph Construction

def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

def infer_embedding_matrix(df: pd.DataFrame):
    if 'DrugBank_ID' not in df.columns:
        raise ValueError("Embeddings CSV must contain 'DrugBank_ID'.")

    ids = df['DrugBank_ID'].astype(str).tolist()

    embedding_col = None
    for candidate in ['embedding', 'embeddings', 'vector', 'embed', 'emb']:
        if candidate in df.columns:
            embedding_col = candidate
            break

    if embedding_col is not None:
        sample = df[embedding_col].dropna().iloc[0]
        if isinstance(sample, str):
            emb_list = df[embedding_col].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
            emb = np.vstack(emb_list.values).astype(np.float32)
        else:
            emb = np.vstack(df[embedding_col].values).astype(np.float32)
    else:
        num_df = df.drop(columns=['DrugBank_ID']).select_dtypes(include=[np.number])
        emb = num_df.values.astype(np.float32)

    return ids, emb

def build_hypergraph_from_embeddings(ids, emb, k=10, sim_threshold=0.0):
    emb_norm = sk_normalize(emb, axis=1)
    sim = cosine_similarity(emb_norm)
    np.fill_diagonal(sim, 0.0)

    hyperedges = {}
    for i in range(len(ids)):
        top_idx = np.argsort(sim[i])[-(k+1):]
        members = [ids[j] for j in top_idx]
        hyperedges[f"he_knn_{i}"] = set(members)

    if sim_threshold > 0.0:
        G = nx.Graph()
        G.add_nodes_from(ids)
        rows, cols = np.where(sim > sim_threshold)
        for a, b in zip(rows, cols):
            if a < b:
                G.add_edge(ids[a], ids[b])
        comps = [list(c) for c in nx.connected_components(G) if len(c) >= 3]
        for ci, comp in enumerate(comps):
            hyperedges[f"he_comp_{ci}"] = set(comp)

    H = hnx.Hypergraph(hyperedges)
    return H, hyperedges

def incidence_matrix(H: hnx.Hypergraph, hyperedges: dict, ids: list, device: torch.device):
    node_index = {n: i for i, n in enumerate(ids)}
    Hm = torch.zeros((len(ids), len(H.edges)), dtype=torch.float32, device=device)
    for j, he in enumerate(H.edges):
        members = hyperedges[he]
        for nname in members:
            if nname in node_index:
                Hm[node_index[nname], j] = 1.0
    return Hm

"""Models (HGNN & Decoder)"""

# Part 3: Models (HGNN & Decoder)

class SimpleHGNN(nn.Module):
    def __init__(self, in_dim, hidden_dim=128, out_dim=128):
        super().__init__()
        self.fc = nn.Linear(in_dim, hidden_dim)
        self.proj = nn.Linear(hidden_dim, out_dim)

    def forward(self, x, H):
        dv = H.sum(dim=1).clamp(min=1.0)
        de = H.sum(dim=0).clamp(min=1.0)
        Dv_inv_sqrt = dv.pow(-0.5).unsqueeze(1)
        De_inv = de.pow(-1.0).unsqueeze(1)

        y = Dv_inv_sqrt * x
        y = H.t() @ y
        y = De_inv * y
        y = H @ y
        y = Dv_inv_sqrt * y

        h = F.relu(self.fc(y))
        z = self.proj(h)
        return z

class PairMLP(nn.Module):
    def __init__(self, dim, hidden=128):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(dim*4, hidden),
            nn.ReLU(),
            nn.Linear(hidden, 1)
        )

    def forward(self, zi, zj):
        feats = torch.cat([zi, zj, torch.abs(zi - zj), zi * zj], dim=-1)
        return self.mlp(feats).squeeze(-1)

"""Training & Evaluation"""

# Part 4: Training & Evaluation (Fixed for your dataset)

def evaluate(z, pairs, labels, id2idx, decoder, device):
    zi, zj, new_labels = [], [], []

    for (d1, d2), lbl in zip(pairs, labels):
        if d1 not in id2idx or d2 not in id2idx:
            continue
        zi.append(z[id2idx[d1]].unsqueeze(0))
        zj.append(z[id2idx[d2]].unsqueeze(0))
        new_labels.append(lbl)

    if len(zi) == 0:  # edge case
        return 0, 0, 0, 0, []

    zi = torch.cat(zi, dim=0).to(device)
    zj = torch.cat(zj, dim=0).to(device)
    labels = torch.tensor(new_labels, dtype=torch.float, device=device)

    with torch.no_grad():
        preds = decoder(zi, zj)

    # turn preds into probabilities
    probs = torch.sigmoid(preds).cpu().numpy()
    labels = labels.cpu().numpy()

    # compute metrics
    from sklearn.metrics import roc_auc_score, average_precision_score, accuracy_score, f1_score

    auc = roc_auc_score(labels, probs)
    aupr = average_precision_score(labels, probs)
    acc = accuracy_score(labels, (probs > 0.5).astype(int))
    f1 = f1_score(labels, (probs > 0.5).astype(int))

    return auc, aupr, acc, f1, probs




# === MAIN PIPELINE ===
set_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# Load embeddings
emb_path = "/content/drive/MyDrive/Explainable DDI/Chemberta-Embeddings.csv"
emb_df = pd.read_csv(emb_path)
ids, emb = infer_embedding_matrix(emb_df)
print(f"Loaded {len(ids)} drugs, dim={emb.shape[1]}")

# Build hypergraph
H, he_map = build_hypergraph_from_embeddings(ids, emb, k=10)
Hm = incidence_matrix(H, he_map, ids, device)
id2idx = {d:i for i,d in enumerate(ids)}
X = torch.tensor(emb, dtype=torch.float32, device=device)

# -------------------------------------------------
# 🔹 Since no real DDI.csv, generate synthetic pairs
# -------------------------------------------------
from itertools import combinations
rng = np.random.default_rng(42)

# positive = top-5 nearest neighbor pairs per drug
sim = cosine_similarity(emb)
np.fill_diagonal(sim, -1)
pos_pairs = []
for i, drug in enumerate(ids):
    top_idx = np.argsort(sim[i])[-5:]
    for j in top_idx:
        pos_pairs.append((drug, ids[j], 1))

# negative = random pairs not in positives
all_set = set(tuple(sorted((a,b))) for a,b,_ in pos_pairs)
neg_pairs = []
while len(neg_pairs) < len(pos_pairs):
    a, b = rng.choice(ids, 2, replace=False)
    key = tuple(sorted((a,b)))
    if key not in all_set:
        neg_pairs.append((a, b, 0))
        all_set.add(key)

pairs = pd.DataFrame(pos_pairs + neg_pairs, columns=['drug1','drug2','label'])
print(f"Synthetic dataset: {len(pairs)} pairs (pos={sum(pairs.label)}, neg={len(pairs)-sum(pairs.label)})")

# Split train/test
train_df, test_df = train_test_split(pairs, test_size=0.2, random_state=42, stratify=pairs['label'])

# -------------------------------------------------
# 🔹 Train HGNN + Decoder
# -------------------------------------------------
hgnn = SimpleHGNN(in_dim=X.shape[1], hidden_dim=128, out_dim=128).to(device)
decoder = PairMLP(dim=128, hidden=128).to(device)
opt = torch.optim.Adam(list(hgnn.parameters()) + list(decoder.parameters()), lr=1e-3)
bce = nn.BCEWithLogitsLoss()

losses = []
for epoch in range(1, 11):
    hgnn.train(); decoder.train()
    z = hgnn(X, Hm)

    zi = z[[id2idx[a] for a in train_df['drug1']]]
    zj = z[[id2idx[b] for b in train_df['drug2']]]
    labels = torch.tensor(train_df['label'].values, dtype=torch.float32, device=device)

    opt.zero_grad()
    logits = decoder(zi, zj)
    loss = bce(logits, labels)
    loss.backward()
    opt.step()
    losses.append(loss.item())

    auc, aupr, acc, f1, _ = evaluate(
        z, zip(test_df['drug1'], test_df['drug2']), test_df['label'], id2idx, decoder, device
    )
    print(f"Epoch {epoch:02d} | Loss={loss.item():.4f} | Test AUC={auc:.4f} | ACC={acc:.4f}")

# -------------------------------------------------
# 🔹 Save plots
# -------------------------------------------------
plt.figure(figsize=(6,4))
plt.plot(losses, marker='o')
plt.title("Training Loss Curve")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True)
plt.savefig("loss_curve.png", dpi=200)
plt.close()
print("Saved loss_curve.png")

"""Training Loss Curve"""

plt.figure(figsize=(7,5))
plt.plot(range(1, len(losses)+1), losses, marker='o', color='dodgerblue')
plt.title("Training Loss over Epochs")
plt.xlabel("Epoch")
plt.ylabel("BCE Loss")
plt.grid(True)
plt.show()



